baseURL = "http://learn.aayushtuladhar.com"
languageCode = "en-us"
title = ""
theme = "hugo-theme-learn"

[params]
  AuthorName = "Aayush Tuladhar"
  GitHubUser = "arttuladhar"
  SidebarRecentLimit = 5
  Subtitle = "Always Learning; Always Improving"
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fas fa-tags'></i> Tags"
url = "/tags"
weight = 30