baseURL = "http://learn.aayushtuladhar.com"
languageCode = "en-us"
title = "Always Learning; Always Improving"
theme = "hugo-theme-learn"

[params]
  AuthorName = "Aayush Tuladhar"
  GitHubUser = "arttuladhar"
  SidebarRecentLimit = 5
  Subtitle = "Always Learning; Always Improving"

[outputs]
home = [ "HTML", "RSS", "JSON"]