baseURL = "http://hello-hugo.aayushtuladhar.com"
languageCode = "en-us"
title = "Learn"
theme = "hugo-theme-learn"

[params]
  AuthorName = "Aayush Tuladhar"
  GitHubUser = "arttuladhar"
  SidebarRecentLimit = 5
  Subtitle = "Hugo, here we come"

[outputs]
home = [ "HTML", "RSS", "JSON"]