--- 
jobs:
  prep:
    docker:
      - image: cibuilds/hugo:latest
    steps:
      - checkout
      - run: "./deploy.sh"
  deploy:
    docker: 
      - image: cibuilds/base
    steps: 
      - attach_workspace: 
          at: my-site
      - run: "ls -lah my-site"
version: 2.1
workflows: 
  main: 
    jobs: 
      - prep
      - deploy: 
          requires: 
            - prep